<?xml version="1.0" encoding="utf-8"?><Database Name="BoutiqueDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-S1C2ODL\SQLEXPRESS;Initial Catalog=BoutiqueDB;Integrated Security=True;Pooling=False" SettingsObjectName="Boutique_jouet.Properties.Settings" SettingsPropertyName="BoutiqueDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.jouet" Member="jouet">
    <Type Name="jouet">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="type" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="cible" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="prix" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="idFournisseur" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="fournisseur_jouet" Member="fournisseur" ThisKey="idFournisseur" OtherKey="id" Type="fournisseur" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.fournisseur" Member="fournisseur">
    <Type Name="fournisseur">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="adresse" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="typeJouet" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tels" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="fournisseur_jouet" Member="jouet" ThisKey="id" OtherKey="idFournisseur" Type="jouet" />
    </Type>
  </Table>
  <Table Name="dbo.client" Member="client">
    <Type Name="client">
      <Column Name="email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.caissier" Member="caissier">
    <Type Name="caissier">
      <Column Name="login" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="nom" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="prenom" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="tel" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="nss" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.administrateur" Member="administrateur">
    <Type Name="administrateur">
      <Column Name="login" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>